name: Label Checker

on:
  pull_request:
    types: [labeled]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if label is 'Merge Ready'
        run: |
          if [ "${{ github.event.label.name }}" != "Merge Ready" ]; then
              echo "❌ Label is not 'Merge Ready'. Exiting with error."
              exit 1
            else
              echo "✅ Label 'Merge Ready' found."
            fi
